apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      containers:
      - name: symfony-container
        image: __IMAGE_NAME__:__TAG__
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: symfony-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: symfony-app
