<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRgWNu1x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRgWNu1x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRgWNu1x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRgWNu1x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRgWNu1x\App_KernelDevDebugContainer([
    'container.build_hash' => 'RgWNu1x',
    'container.build_id' => '459f045f',
    'container.build_time' => 1723996153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRgWNu1x');
