<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDlU2LyR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDlU2LyR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDlU2LyR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDlU2LyR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDlU2LyR\App_KernelDevDebugContainer([
    'container.build_hash' => 'DlU2LyR',
    'container.build_id' => 'd949a6d0',
    'container.build_time' => 1723761948,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDlU2LyR');
