<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8TJCRej\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8TJCRej/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8TJCRej.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8TJCRej\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8TJCRej\App_KernelDevDebugContainer([
    'container.build_hash' => '8TJCRej',
    'container.build_id' => '6d395fa6',
    'container.build_time' => 1738197387,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8TJCRej');
